# Generated by Django 2.1.1 on 2018-10-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='Poster',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
