# Generated by Django 2.1.1 on 2018-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0002_movies_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='display',
            name='Screen_number',
        ),
        migrations.RemoveField(
            model_name='display',
            name='movie_id',
        ),
        migrations.AlterField(
            model_name='movies',
            name='Poster',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.RemoveField(
            model_name='screens',
            name='type',
        ),
        migrations.AddField(
            model_name='screens',
            name='type',
            field=models.CharField(blank=True, choices=[('2d', '2D'), ('3D', '3D'), ('IMAX', 'Imax')], max_length=4),
        ),
        migrations.DeleteModel(
            name='Display',
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
