# Generated by Django 2.1.1 on 2018-10-02 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0004_auto_20181002_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcontact',
            name='contact',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Contact',
        ),
        migrations.AddField(
            model_name='customer',
            name='Contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='cinema_management.CustContact'),
            preserve_default=False,
        ),
    ]
