# Generated by Django 2.1.1 on 2018-10-02 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0005_auto_20181002_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Contact',
        ),
        migrations.AlterField(
            model_name='custcontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_management.Customer'),
        ),
    ]
