# Generated by Django 2.1.1 on 2018-10-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0006_auto_20181002_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custcontact',
            old_name='contact',
            new_name='Customer_id',
        ),
        migrations.AddField(
            model_name='custcontact',
            name='Contact',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
