# Generated by Django 2.1.1 on 2018-10-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0007_auto_20181002_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screens',
            name='type',
            field=models.CharField(choices=[('2d', '2D'), ('3D', '3D'), ('IMAX', 'Imax')], max_length=4),
        ),
    ]
