# Generated by Django 2.1.1 on 2018-10-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0008_auto_20181002_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.IntegerField(max_length=10)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_management.Customer')),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_management.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='custcontact',
            name='Customer_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='Screen',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='movie_id',
        ),
        migrations.AddField(
            model_name='movies',
            name='Status',
            field=models.CharField(choices=[('U', 'Upcoming'), ('C', 'Currently Airing'), ('A', 'Aired')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CustContact',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
