# Generated by Django 2.1.1 on 2018-10-02 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0009_auto_20181002_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Contact', models.IntegerField(max_length=10)),
                ('Staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema_management.Staff')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Staff',
        ),
    ]
