# Generated by Django 2.1.1 on 2018-10-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0012_auto_20181003_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='number',
            field=models.CharField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
