# Generated by Django 2.1.1 on 2018-10-03 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0013_seats_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seats',
            options={'verbose_name_plural': 'Seats'},
        ),
        migrations.AddField(
            model_name='seats',
            name='location',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
