# Generated by Django 2.1.1 on 2018-10-05 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0014_auto_20181003_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seats',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema_management.Customer'),
        ),
    ]
