# Generated by Django 2.1.1 on 2018-10-05 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_management', '0015_auto_20181005_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='seats',
            name='Status',
            field=models.CharField(choices=[('A', 'Available'), ('B', 'Booked')], default='B', max_length=1),
            preserve_default=False,
        ),
    ]
